import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import Layout from '../../components/layout'
import styles from './forms.module.css'

export default function Form( {...props}) {
  return (
    <Layout home>
      <Head>
        <title>Forms</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main>
        <h1 className={styles.title}>
          Forms
        </h1>
        <div className={styles.container}></div>
        <div className={styles.formBox}>
          <div className={styles.grid}>
            <Link href="/forms/canada-customs-invoice"><a className={styles.card}>
              <h2>Canada Customs Invoice &rarr;</h2>
              <p>Canadian Customs Invoice</p>
            </a></Link>
          </div>
          <div className={styles.grid}>
            <Link href="/forms/us-customs-invoice"><a className={styles.card}>
              <h2>US Customs Invoice &rarr;</h2>
              <p>US Customs Invoice</p>
            </a></Link>
          </div>

          <div className={styles.grid}>
            <Link href="/forms/us-customs-invoice"><a className={styles.card}>
              <h2>US Customs Invoice &rarr;</h2>
              <p>US Customs Invoice</p>
            </a></Link>
          </div>

          <div className={styles.grid}>
            <Link href="/forms/us-customs-invoice"><a className={styles.card}>
              <h2>US Customs Invoice &rarr;</h2>
              <p>US Customs Invoice</p>
            </a></Link>
          </div>
          <div className={styles.grid}>
            <Link href="/forms/canada-customs-invoice"><a className={styles.card}>
              <h2>Canada Customs Invoice &rarr;</h2>
              <p>Canadian Customs Invoice</p>
            </a></Link>
          </div>
          <div className={styles.grid}>
            <Link href="/forms/us-customs-invoice"><a className={styles.card}>
              <h2>US Customs Invoice &rarr;</h2>
              <p>US Customs Invoice</p>
            </a></Link>
          </div>

          <div className={styles.grid}>
            <Link href="/forms/us-customs-invoice"><a className={styles.card}>
              <h2>US Customs Invoice &rarr;</h2>
              <p>US Customs Invoice</p>
            </a></Link>
          </div>

          <div className={styles.grid}>
            <Link href="/forms/us-customs-invoice"><a className={styles.card}>
              <h2>US Customs Invoice &rarr;</h2>
              <p>US Customs Invoice</p>
            </a></Link>
          </div>
        </div>
       </main>
    </Layout>
    )
}